{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "service.labels.standard" . | indent 4 }}
spec:
  selector:
    {{- include "service.labels.standard" . | indent 4 }}
  type: {{.Values.service.type }}
  ports:
  - name: tcp
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: {{ .Values.service.protocol }}
    {{- if (and (eq .Values.service.type "NodePort" ) .Values.service.nodePort) }}
    nodePort: {{ .Values.service.nodePort}}
    {{- end }}
{{- end }}
